### ISSUE TITLE
 I want to read apds9960 data on androidthings

### ISSUE THREAD

**Issue by love-bk** [sparkfun/SparkFun_APDS-9960_Sensor_Arduino_Library#10]
do you have any good suggestions?

**Comment by loricrotser** [comment]
Apologies for the long reply time, and unfortunately, I don't have any good suggestions on this. There might be someone on the [SparkFun forums](https://forum.sparkfun.com/index.php) that has some ideas - the github issues are primarily for bug fixes and hardware issues. 

Good luck!
