### ISSUE TITLE
why only  APDS9960_GFIFO_U register is alone read ? line no:504

### ISSUE THREAD

**Issue by baijuraj** [sparkfun/SparkFun_APDS-9960_Sensor_Arduino_Library#4]
In line no: 504 of SparkFun_APDS9960.cpp file, only APDS9960_GFIFO_U register is read, why not the other registers like,
APDS9960_GFIFO_D
APDS9960_GFIFO_L
APDS9960_GFIFO_R
are not read while determining the gesture.

Anyone please provide me a suggestion...

**Comment by MartyMacGyver** [comment]
This is an old question, but refer to the [datasheet](https://docs.broadcom.com/docs/AV02-4191EN) - on page 33 we see the FIFO reads are in 4-byte blocks, corresponding to GFIFO_U, GFIFO_D, GFIFO_L and then GFIFO_R. A few lines below the code you mention in `SparkFun_APDS9960::readGesture()` you will see this data being decoded. Therefore all four registers get decoded properly.

**Comment by ShawnHymel** [comment]
This is correct. 4 bytes of data are read starting with the GFIFO_U address. Thanks, @MartyMacGyver
