### ISSUE TITLE
Problem with NANO

### ISSUE THREAD

**Issue by Oxmaster** [sparkfun/SparkFun_APDS-9960_Sensor_Arduino_Library#6]
Hey guys, not sure if anyone is still looking here but I have an issue with not original SparkFun APDS-9960 module but a "knock off".

Strange thing is that the module works perfectly on my UNO board but it doesn't on my NANO for some reason.

In gestureTest sketch NANO immediately receives interrupt signal and stats processing, even though there wasn't any input. Then it's stuck in the while(1) (while the data is valid) loop never escaping it.

I ran in debug mode my UNO and NANO, here are results:
UNO: https://pastebin.com/rexnAkSN
NANO: https://pastebin.com/7ERh3UwZ

I don't expect anything, but it's worth trying.

**Comment by ShawnHymel** [comment]
Only thing I can think is that it it could be a power issue. See if you can power the APDS-9960 board off a different 3.3V power supply. From what I can tell on the [Nano's schematic](https://www.arduino.cc/en/uploads/Main/ArduinoNano30Schematic.pdf), the 3.3V is sourced from the FTDI chip, which is really not meant to source a lot of current.

**Comment by Oxmaster** [comment]
Thanks for the reply!

That's would be nice if power was an issue, but I already did all the testing with power, I added more details in my arduino.cc post https://forum.arduino.cc/index.php?topic=483921.0

I have 2nd NANO but that one is already integrated in a project, I think that I will need to tear it from it and check if it's my NANO or NANO in general.
