### ISSUE TITLE
LED_BOOST 

### ISSUE THREAD

**Issue by dburgessMethven** [sparkfun/SparkFun_APDS-9960_Sensor_Arduino_Library#7]
Hi in the datasheet for the chip I see that LED_BOOST can bump current up  to 300% , but looking through the library it looks by default it is already set at 300%. Am I reading the library right?

**Comment by loricrotser** [comment]
Hi! Apologies for the long wait time, I've just been assigned this bug. You are indeed reading the library correctly - LED_BOOST is initialized to 300 by default. There is a function available to change the LED_BOOST setting; SparkFun_APDS9960::setLEDBoost(uint8_t boost). So you can change it in your sketch. 

Hope this is helpful! If you need further technical support, feel free to head over to the [SparkFun forums](https://forum.sparkfun.com/index.php) - they'll be able to help you out. Thank you!
